"""Strategy protocol for backtesting."""

from __future__ import annotations

from typing import Protocol

from core.types import Candle, SignalSide


class Signal:
    """Trading signal generated by a strategy."""

    def __init__(self, side: SignalSide, strength: int = 50):
        self.side = side
        self.strength = strength


class Strategy(Protocol):
    """Protocol for backtesting strategies.
    
    Strategies implement on_candle to generate trading signals
    based on current candle and calculated indicators.
    """

    def on_candle(self, candle: Candle, indicators: dict) -> Signal | None:
        """Process a candle and return a trading signal.
        
        Args:
            candle: Current OHLCV candle
            indicators: Dict of computed indicators (e.g., {'rsi': 45.2})
            
        Returns:
            Signal with side (BUY/SELL/HOLD) or None for no action
        """
        ...
